//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ck_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cksysdb : DbContext
    {
        public cksysdb()
            : base("name=cksysdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addresses> addresses { get; set; }
        public virtual DbSet<branches> branches { get; set; }
        public virtual DbSet<building_permit> building_permit { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<delivery_status> delivery_status { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<installation> installation { get; set; }
        public virtual DbSet<lead_log_file> lead_log_file { get; set; }
        public virtual DbSet<lead_source> lead_source { get; set; }
        public virtual DbSet<leads> leads { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<project_class> project_class { get; set; }
        public virtual DbSet<project_status> project_status { get; set; }
        public virtual DbSet<project_type> project_type { get; set; }
        public virtual DbSet<rates> rates { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tasks> tasks { get; set; }
        public virtual DbSet<tasks_installation> tasks_installation { get; set; }
        public virtual DbSet<taxes> taxes { get; set; }
        public virtual DbSet<total_cost> total_cost { get; set; }
        public virtual DbSet<users_types> users_types { get; set; }
    }
}
